### ISSUE TITLE
Autoencoder example in README raises an AttributeError

### ISSUE THREAD

**Issue by pnkraemer** [MachineLearningLifeScience/stochman#26]
Hi there :wave: 

I am unsure whether this is desired behaviour, but I thought I'd raise this issue anyway: 

When running the autoencoder example in the README, I get an AttributeError

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kraemer/Projects/stochman-project/stochman/stochman/manifold.py", line 310, in connecting_geodesic
    success = geodesic_minimizing_energy(curve, self)
  File "/home/kraemer/Projects/stochman-project/stochman/stochman/geodesic.py", line 91, in geodesic_minimizing_energy
    opt.step(closure=closure)
  File "/home/kraemer/Projects/stochman-project/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/kraemer/Projects/stochman-project/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/kraemer/Projects/stochman-project/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "/home/kraemer/Projects/stochman-project/stochman/stochman/geodesic.py", line 84, in closure
    loss = manifold.curve_energy(curve(alpha)).mean()
  File "/home/kraemer/Projects/stochman-project/stochman/stochman/manifold.py", line 444, in curve_energy
    emb_curve = self.embed(curve)  # BxNxD
  File "<stdin>", line 3, in embed
AttributeError: 'Autoencoder' object has no attribute 'decode'
```

I am working with stochman version 0.3.0 and toch version 1.13.1, if that matters. 

What am I misunderstanding?

**Comment by miguelgondu** [comment]
Hi Nicholas!

I think there might be a misunderstanding about the example in the readme. If I'm not mistaken, I think it should be read like this:

```python
import torch
from stochman.manifold import EmbeddedManifold

class Autoencoder(EmbeddedManifold):
    '''
    This is an autoencoder that you have already implemented,
    so it should come with its own self.encode and self.decode
    methods implemented.

    In this particular example, we are expecting you to have a
    self.decode method.
    '''
    def decode(z: torch.Tensor, jacobian: bool = False) -> torch.Tensor:
        # Implement your decoding logic here.
        ...

    def embed(self, c, jacobian = False):
        '''
        The EmbeddedManifold is expecting an `embed` method,
        which corresponds to a smooth map between the latent space
        and data space (i.e. the decoder in the case of Autoencoders).

        If you would like to compute the metric associated with this
        embedding, we are expecting you to return the Jacobian as
        the second argument when `jacobian=True`.
        '''
        return self.decode(c)
        
model = Autoencoder()
p0, p1 = torch.randn(1, 2), torch.randn(1, 2)
c, _ = model.connecting_geodesic(p0, p1)  # geodesic between two random points
```

Let me know if you would like me to provide a minimal working example of how to use `EmbeddedManifold`s.

Cheers!

**Comment by pnkraemer** [comment]
Cool, thanks! 

I'll consider this resolved :)
